// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pokemon-card': string;
  'pokemon-card__img': string;
  'pokemon-card__img-container': string;
  'pokemon-card__img-container--fire': string;
  'pokemon-card__img-container--grass': string;
  'pokemon-card__img-container--water': string;
  'pokemon-card__info-container': string;
  'pokemon-card__stat': string;
  'pokemon-card__stat-container': string;
  'pokemon-card__stat-list': string;
  'pokemon-card__stat-title': string;
  'pokemon-card__title': string;
  'pokemon-card__type-badge': string;
  'pokemon-card__type-badge--first': string;
  'pokemond-card__types-list': string;
}
export const cssExports: CssExports;
export default cssExports;
