// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  cloud: string;
  cloudBig: string;
  parallax: string;
  pikachu: string;
  pokeBall: string;
  smallPokeBall: string;
}
export const cssExports: CssExports;
export default cssExports;
