// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  'button--full-width': string;
  'button--small': string;
  'button--yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
