// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  heading: string;
  'heading-h1': string;
  'heading-h2': string;
  'heading-h3': string;
  'heading-h4': string;
  'heading-h5': string;
  'heading-h6': string;
}
export const cssExports: CssExports;
export default cssExports;
