// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  'header__content-wrapper': string;
  header__navigation: string;
  'header__navigation-item': string;
  'header__navigation-item--active': string;
  'header__navigation-link': string;
}
export const cssExports: CssExports;
export default cssExports;
