// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  footer: string;
  'footer__content-wrapper': string;
  'footer__navigation-list': string;
}
export const cssExports: CssExports;
export default cssExports;
